codecov:
  strict_yaml_branch: dev
coverage:
  status:
    project:
      default:
        threshold: 0%
        if_no_uploads: failure
        if_ci_failed: failure
    patch: off
    changes:
      default:
        set_pending: no
        if_no_uploads: failure
        if_ci_failed: failure
        only_pulls: no
comment:
  layout: "header, diff, changes"
