codecov:
  strict_yaml_branch: dev
coverage:
  status:
    project:
      default:
        threshold: 0%
        if_no_uploads: failure
        if_ci_failed: failure
    patch:off
    changes:
      default:
        if_no_uploads: failure
        if_ci_failed: failure
comment:
  layout: "header, diff, changes"