language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

branches:
  only:
  - master
  - dev

compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - clang-3.7
    - doxygen
    - graphviz
env:
  global:
  - CXXOMPILER: clang++-3.7
  - CCOMPILER: clang-3.7
  - GH_REPO_NAME: CyberEngineMkIII
  - DOXYFILE: $TRAVIS_BUILD_DIR/BuildScripts/Doxygen/CyberEngineMkIIIDoxy.cfg
  - GH_REPO_REF: github.com/CyberbossJHCB/CyberEngineMkIII.git
  matrix:
  - BUILD_RELEASE: false
  - BUILD_RELEASE: true

script: 
- BuildScripts/Travis/Travis.sh
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then BuildScripts/Travis/TravisCheckDox.sh; fi

after_success: 
- if [[ "$BUILD_RELEASE" != "true" ]]; then bash <(curl -s https://codecov.io/bash); fi
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then BuildScripts/Travis/TravisGenDox.sh; fi