language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

branches:
  only:
  - master
  - dev

compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - clang-3.7
    - graphviz
env:
  global:
  - CXXOMPILER: clang++-3.7
  - CCOMPILER: clang-3.7
  - GH_REPO_NAME: CyberEngineMkIII
  - DOXYFILE: $TRAVIS_BUILD_DIR/BuildScripts/Doxygen/CyberEngineMkIIIDoxy.cfg
  - GH_REPO_REF: github.com/CyberbossJHCB/CyberEngineMkIII.git
  matrix:
  - BUILD_RELEASE: false
  - BUILD_RELEASE: true

install:
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/llvm-cov /usr/local/bin/llvm-cov; fi
- wget https://github.com/doxygen/doxygen/archive/Release_1_8_12.tar.gz
- gunzip Release_1_8_12.tar.gz
- tar -xvf Release_1_8_12.tar
- cd Release_1_8_12
- mkdir build
- cd build
- cmake -G "Unix Makefiles" ..
- make install

script: 
- BuildScripts/Travis/Travis.sh
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then BuildScripts/Travis/TravisCheckDox.sh; fi

after_success:
- BuildScripts/Coverage/run-lcov.sh
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then BuildScripts/Travis/TravisGenDox.sh; fi