language: cpp
sudo: required
dist: trusty

branches:
  only:
  - master
  - dev

compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - clang-3.7
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
env:
  global:
  - CXXOMPILER: clang++-3.7
  - CCOMPILER: clang-3.7
  - GH_REPO_NAME: CyberEngineMkIII
  - DOXYFILE: $TRAVIS_BUILD_DIR/BuildScripts/Doxygen/CyberEngineMkIIIDoxy.cfg
  - GH_REPO_REF: github.com/CyberbossJHCB/CyberEngineMkIII.git
  matrix:
  - BUILD_RELEASE: false
  - BUILD_RELEASE: true
script: 
- BuildScripts/Travis/Travis.sh
- BuildScripts/Travis/TravisCheckDox.sh
after_success: BuildScripts/Travis/TravisGenDox.sh