language: cpp
sudo: required
dist: trusty

os:
  - linux
  - osx

branches:
  only:
  - master
  - dev

compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - clang-3.7
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
env:
  global:
  - COMPILER: clang++-3.7
  - GH_REPO_NAME: CyberEngineMkIII
  - DOXYFILE: $TRAVIS_BUILD_DIR/BuildScripts/Doxygen/CyberEngineMkIIIDoxy.cfg
  - GH_REPO_REF: github.com/CyberbossJHCB/CyberEngineMkIII.git
script: 
- BuildScripts/Travis/Travis.sh
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then BuildScripts/Travis/TravisCheckDox.sh; fi
after_success: 
- if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then BuildScripts/Travis/TravisGenDox.sh; fi