language: cpp
sudo: required
dist: trusty

branches:
  only:
  - master
  - dev

compiler: clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
	- clang-3.7
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphviz
env:
- COMPILER=clang++-3.7
  global:
  - GH_REPO_NAME: CyberEngineMkIII
  - DOXYFILE: $TRAVIS_BUILD_DIR/BuildScripts/Doxygen/CyberEngineMkIIIDoxy.cfg
  - GH_REPO_REF: github.com/CyberbossJHCB/CyberEngineMkIII.git
script: BuildScripts/Travis/Travis.sh
after_success:
- cd $TRAVIS_BUILD_DIR
- BuildScripts/Doxygen/TravisGenDox.sh