os: Visual Studio 2015

branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive

build: 
  project: CyberEngineMkIII.sln

before_test:
- powershell -Command "BuildScripts/Appveyor/InstallCatchAdapter.ps1"

test_script:
- C:\\Program Files\ (x86)\\Microsoft\ Visual\ Studio\ 14.0\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe /logger:Appveyor /UseVsixExtensions:true /Platform:x64 /inIsolation /Enablecodecoverage Output/bin/CyberEngineMkIIITester.exe