os: Visual Studio 2015

branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive
- ps "BuildScripts/Appveyor/InstallCatchAdapter.ps1"

build: 
  project: CyberEngineMkIII.sln

test:
- vstest.console /logger:Appveyor /UseVsixExtensions:true Output/bin/CyberEngineMkIIITester.exe /xml cyb-test-results.xml