os: Visual Studio 2015

branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive

build: 
  project: CyberEngineMkIII.sln

before_test:
- powershell -Command "BuildScripts/Appveyor/InstallCatchAdapter.ps1"

test_script:
- vstest.console /logger:Appveyor /UseVsixExtensions:true /Enablecodecoverage Output/bin/CyberEngineMkIIITester.exe