os: Visual Studio 2015

branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive

build: 
  project: CyberEngineMkIII.sln

test_script:
- powershell -Command "BuildScripts/Appveyor/InstallCatchAdapter.ps1"