os: Visual Studio 2015

branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive

build: 
  parallel: true
  project: CyberEngineMkIII.sln
  
test_script:
- vstest.console.exe /logger:Appveyor /Platform:x64 /UseVsixExtensions:true /Enablecodecoverage Output/bin/CyberEngineMkIIITester.exe