branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive
- ps "BuildScripts/Appveyor/InstallCatchAdapter.ps1"

build: 
  project: CyberEngineMkIII.sln