os: Visual Studio 2015

branches:
  only:
  - master
  - dev

platform:
- x64

configuration:
- Debug
- Release

install:
- git submodule update --init --recursive

build: 
  parallel: true
  project: CyberEngineMkIII.sln
  
before_test:
- powershell -Command "BuildScripts/Appveyor/InstallCatchAdapter.ps1"
  
test_script:
- vstest.console.exe /logger:Appveyor /Platform:x64 /UseVsixExtensions:true /inIsolation /Settings:"Test/CoverageExclusions.runsettings" Output/bin/CyberEngineMkIIITester.exe